const quizData = [
    // --- KATEGORIE A: PŘEDPISY (1-40) ---
    { "cat": "a", "q": "Kdo provádí státní kontrolu elektronických komunikací?", "a": "Český telekomunikační úřad", "others": ["Ministerstvo dopravy", "Úřad pro civilní letectví", "Řízení letového provozu", "Ministerstvo vnitra"] },
    { "cat": "a", "q": "Kdo je povinen se podrobit zkoušce k prokázání odborné způsobilosti?", "a": "Osoba, která obsluhuje vysílací rádiová zařízení", "others": ["Vlastník letadla bez ohledu na to, zda rádio používá", "Každý držitel pilotního průkazu", "Pouze pozemní personál letiště", "Osoba odpovědná za údržbu avioniky"] },
    { "cat": "a", "q": "Jaký průkaz odborné způsobilosti je vyžadován pro obsluhu letecké pohyblivé stanice v češtině?", "a": "Omezený průkaz radiotelefonisty letecké pohyblivé služby (OFL)", "others": ["Všeobecný průkaz radiotelefonisty (VFL)", "Průkaz operátora námořní služby", "Průkaz pozemního radiolokátorového operátora", "Amatérský průkaz třídy A"] },
    { "cat": "a", "q": "Kým je vydáván průkaz odborné způsobilosti?", "a": "Českým telekomunikačním úřadem", "others": ["Leteckou amatérskou asociací", "Úřadem pro civilní letectví", "Ministerstvem průmyslu a obchodu", "Radioklubem České republiky"] },
    { "cat": "a", "q": "Jaká je doba platnosti průkazu odborné způsobilosti?", "a": "10 let", "others": ["5 let", "20 let", "Doba platnosti je neomezená", "Platí do dovršení 65 let věku"] },
    { "cat": "a", "q": "Kdy lze požádat o prodloužení platnosti průkazu odborné způsobilosti?", "a": "Nejdříve 12 měsíců a nejpozději 1 měsíc před vypršením platnosti", "others": ["Kdykoliv po vypršení platnosti do 2 let", "Nejdříve 3 měsíce před vypršením platnosti", "Pouze v posledních 14 dnech platnosti", "V den výročí vydání průkazu"] },
    { "cat": "a", "q": "Jakou podmínku musí žadatel splnit pro prodloužení platnosti průkazu?", "a": "Prokázat, že v uplynulých 10 letech nejméně 1 rok vykonával příslušnou obsluhu", "others": ["Absolvovat znovu ústní zkoušku", "Předložit potvrzení o lékařské prohlídce", "Uhradit poplatek 5000 Kč", "Doložit nálet minimálně 100 hodin ročně"] },
    { "cat": "a", "q": "Co se stane, pokud držitel průkazu odevzdá žádost o prodloužení po stanovené lhůtě?", "a": "Musí vykonat novou zkoušku", "others": ["Průkaz je prodloužen s penále", "Průkaz propadá bez možnosti obnovy", "Platnost se prodlouží automaticky o 1 rok", "Držiteli je udělena důtka"] },
    { "cat": "a", "q": "Kdo stanovuje podmínky pro udělení průkazu odborné způsobilosti?", "a": "Prováděcí právní předpis", "others": ["Ředitel letiště Praha-Ruzyně", "Statutární zástupce aeroklubu", "Předpis L-13", "Mezinárodní telekomunikační unie (ITU)"] },
    { "cat": "a", "q": "Při jaké činnosti musí mít osoba průkaz u sebe?", "a": "Při obsluze vysílacího rádiového zařízení", "others": ["Jen při letech do zahraničí", "Pouze při výcviku", "Při každém vstupu na plochu letiště", "Při nákupu palubní radiostanice"] },
    { "cat": "a", "q": "Může být držitelem průkazu osoba s pravomocně uloženým trestem zákazu činnosti obsluhy?", "a": "Ne, po dobu výkonu tohoto trestu", "others": ["Ano, pokud zaplatí kauci", "Ano, ale pouze v doprovodu instruktora", "Pouze v případě nouze", "Ano, zákaz se týká jen řízení, ne vysílání"] },
    { "cat": "a", "q": "Jaká je minimální věková hranice pro získání průkazu OFL?", "a": "15 let", "others": ["12 let", "16 let", "18 let", "Není stanovena"] },
    { "cat": "a", "q": "Který právní předpis upravuje přestupky v oblasti elektronických komunikací?", "a": "Zákon o elektronických komunikacích", "others": ["Trestní zákoník", "Občanský zákoník", "Zákon o provozu na pozemních komunikacích", "Letecký zákon"] },
    { "cat": "a", "q": "Co musí žadatel doložit k žádosti o vydání průkazu?", "a": "Doklad o úspěšném vykonání zkoušky a fotografii", "others": ["Potvrzení o bezúhonnosti", "Lékařské potvrzení o sluchu", "Výpis z rejstříku trestů", "Potvrzení o vlastnictví letadla"] },
    { "cat": "a", "q": "Kdo rozhoduje o odejmutí průkazu v případě ztráty odborné způsobilosti?", "a": "Český telekomunikační úřad", "others": ["Policie ČR", "Letecká inspekce", "Vojenské letectvo", "Soudce okresního soudu"] },
    { "cat": "a", "q": "Jakým způsobem se prokazuje totožnost při zkoušce?", "a": "Platným dokladem totožnosti", "others": ["Čestným prohlášením", "Svědectvím instruktora", "Pilotním průkazem", "Vstupní kartou na letiště"] },
    { "cat": "a", "q": "Kdy zaniká platnost průkazu odborné způsobilosti?", "a": "Uplynutím doby platnosti v něm uvedené", "others": ["Při každé změně trvalého bydliště", "Při prodeji letadla", "Po roce nepoužívání radiostanice", "Při změně typu vysílačky"] },
    { "cat": "a", "q": "Jak se postupuje při změně jména nebo příjmení držitele průkazu?", "a": "Držitel požádá ČTÚ o vydání nového průkazu", "others": ["Jméno se v průkazu přepíše ručně", "Průkaz se stává neplatným bez náhrady", "Není třeba nic hlásit", "Průkaz se odevzdá na policii"] },
    { "cat": "a", "q": "Je průkaz OFL platný i pro komunikaci v angličtině?", "a": "Ne, tento průkaz opravňuje pouze ke komunikaci v českém jazyce", "others": ["Ano, v celé Evropě", "Ano, ale jen při letech nad 10 000 stop", "Ano, pokud má pilot zkoušku ICAO English", "Pouze na mezinárodních letištích v ČR"] },
    { "cat": "a", "q": "Jaký dokument opravňuje k provozu rámiové stanice v letadle?", "a": "Licence (Průkaz) stanice", "others": ["Technický průkaz letadla", "Záruční list výrobce", "Pojištění odpovědnosti", "Osvědčení o letové způsobilosti"] },
    { "cat": "a", "q": "Může být radiostanice v letadle použita k soukromým hovorům?", "a": "Ne, je určena výhradně pro zajištění bezpečnosti a pravidelnosti letů", "others": ["Ano, pokud nerušíte ostatní", "Pouze v noci", "Ano, v pásmu 123,45 MHz", "Jen se souhlasem dispečera"] },
    { "cat": "a", "q": "Kdo zodpovídá za technický stav rádiové stanice na palubě?", "a": "Vlastník nebo provozovatel stanice", "others": ["Výrobce vysílačky", "První pilot, který letí ten den", "Český telekomunikační úřad", "Hasičský záchranný sbor"] },
    { "cat": "a", "q": "Jaké sankce hrozí za porušení telekomunikačního tajemství?", "a": "Pokuta nebo trestní stíhání", "others": ["Domluva na místě", "Zákaz létání na 14 dní", "Zabavení mobilního telefonu", "Povinnost omluvit se v rádiu"] },
    { "cat": "a", "q": "Z čeho se skládá zkouška odborné způsobilosti?", "a": "Z písemného testu a ústní/praktické části", "others": ["Pouze z praktického letu", "Z psychotestů a běhu", "Jen z vyplnění dotazníku", "Z testu z angličtiny a navigace"] },
    { "cat": "a", "q": "Co je to telekomunikační tajemství?", "a": "Povinnost zachovávat mlčenlivost o obsahu a účastnících zpráv", "others": ["Znalost tajných kódů armády", "Heslo pro vstup do systému ČTÚ", "Schopnost šifrovat vysílání", "Zákaz mluvení s médii"] },
    { "cat": "a", "q": "Může být průkaz OFL vydán bez zkoušky?", "a": "Ne, zkouška je zákonnou podmínkou", "others": ["Ano, držitelům řidičského průkazu", "Ano, studentům technických univerzit", "Pouze za poplatek 10 000 Kč", "Ano, po 20 letech praxe v armádě"] },
    { "cat": "a", "q": "Kde je definován rozsah znalostí ke zkoušce?", "a": "Ve zkušebním řádu vydaném ČTÚ", "others": ["V učebnici pro autoškoly", "V palubním deníku letadla", "V obchodních podmínkách operátora", "V mapě leteckých tratí"] },
    { "cat": "a", "q": "Kdo může být přítomen u zkoušky?", "a": "Zkušební komise a zkoušený", "others": ["Široká veřejnost", "Pouze rodina zkoušeného", "Zástupci televize", "Kdokoliv, kdo zaplatí vstupné"] },
    { "cat": "a", "q": "Jak dlouho platí výsledek úspěšné zkoušky pro vydání průkazu?", "a": "90 dnů", "others": ["1 rok", "10 let", "Navždy", "30 dnů"] },
    { "cat": "a", "q": "Co dělat při ztrátě průkazu odborné způsobilosti?", "a": "Požádat ČTÚ o duplikát", "others": ["Vystavit si vlastní náhradní doklad", "Nahlásit to na obecní úřad", "Nedělat nic a létat bez něj", "Koupit si nový průkaz v papírnictví"] },
    { "cat": "a", "q": "Zaniká platnost průkazu při změně trvalého pobytu?", "a": "Ne, ale držitel je povinen ohlásit změnu údajů do 30 dnů", "others": ["Ano, platnost končí dnem přestěhování", "Pouze pokud se stěhuje do jiného kraje", "Ano, musí se dělat nová zkouška", "Průkaz platí dál i se starou adresou bez hlášení"] },
    { "cat": "a", "q": "Jaký je účel státní kontroly v radiokomunikacích?", "a": "Zajištění nerušeného provozu radiokomunikačních služeb", "others": ["Výběr poplatků za vysílání", "Sledování obsahu soukromých hovorů", "Kontrola čistoty v letadle", "Měření rychlosti letadel radarem"] },
    { "cat": "a", "q": "Kdo může provádět revizi radiostanice?", "a": "Oprávněná servisní organizace nebo technik", "others": ["Pilot před každým startem", "Policie ČR", "Hasiči", "Každý držitel průkazu OFL"] },
    { "cat": "a", "q": "Musí být radiostanice v letadle schváleného typu?", "a": "Ano, musí splňovat technické standardy a mít certifikaci", "others": ["Ne, v amatérských letadlech může být cokoli", "Pouze pokud létá v noci", "Jen pokud má letadlo více než 4 sedadla", "Pouze u proudových letadel"] },
    { "cat": "a", "q": "Jak dlouho se musí uchovávat deník radiostanice?", "a": "Podle vnitřních předpisů provozovatele, obvykle 3 měsíce", "others": ["1 rok", "10 let", "Není třeba uchovávat", "Do příští revize radiostanice"] },
    { "cat": "a", "q": "Kdo může nahlížet do průkazu odborné způsobilosti?", "a": "Orgány státní kontroly a pověřené osoby", "others": ["Kterýkoliv jiný pilot", "Pouze rodinní příslušníci", "Zaměstnanci pošty", "Provozovatel čerpací stanice"] },
    { "cat": "a", "q": "Co je považováno za zneužití tísňového signálu?", "a": "Vysílání signálu MAYDAY v jiném případě než při vážném ohrožení", "others": ["Vysílání tísně na nesprávném kmitočtu", "Odpovídání na tísňové volání jiné stanice", "Vysílání v noci", "Zkouška tísňového tlačítka v hangáru"] },
    { "cat": "a", "q": "Může držitel průkazu OFL obsluhovat námořní stanice?", "a": "Ne, průkaz platí pouze pro leteckou pohyblivou službu", "others": ["Ano, v dosahu pobřeží", "Ano, po doplňkovém školení", "Ano, ale jen v mezinárodních vodách", "Pouze pokud je loď vybavena leteckým kmitočtem"] },
    { "cat": "a", "q": "Změna jména držitele průkazu vyžaduje:", "a": "Podání žádosti o vydání nového průkazu s aktuálními údaji", "others": ["Ruční přepsání v původním průkazu", "Zrušení průkazu bez náhrady", "Není třeba nic řešit", "Oznámení pouze instruktorovi"] },
    { "cat": "a", "q": "Poplatek za vydání duplikátu průkazu je:", "a": "Stanoven zákonem o správních poplatcích", "others": ["Vždy zdarma", "10 000 Kč", "Smluvní cena", "Dobrovolný příspěvek"] },

    // --- KATEGORIE B: PROVOZ (41-100) ---
    { "cat": "b", "q": "Jaký signál má absolutní přednost?", "a": "Tísňový signál (MAYDAY)", "others": ["Pilnostní signál (PAN PAN)", "Zajišťovací signál (SECURITE)", "Výzva k přistání", "Meteorologická zpráva"] },
    { "cat": "b", "q": "Jak se hláskuje písmeno 'A'?", "a": "Alfa", "others": ["Adam", "Apple", "America", "Alpha"] },
    { "cat": "b", "q": "Jak se hláskuje písmeno 'B'?", "a": "Bravo", "others": ["Boston", "Beer", "Bara", "Baker"] },
    { "cat": "b", "q": "Jak se hláskuje písmeno 'C'?", "a": "Charlie", "others": ["Canada", "Casper", "Cyril", "Coca"] },
    { "cat": "b", "q": "Jak se hláskuje písmeno 'D'?", "a": "Delta", "others": ["David", "Denmark", "Dollar", "Dina"] },
    { "cat": "b", "q": "Jak se hláskuje písmeno 'E'?", "a": "Echo", "others": ["Emil", "Europe", "Easy", "Eagle"] },
    { "cat": "b", "q": "Jak se hláskuje písmeno 'F'?", "a": "Foxtrot", "others": ["Franta", "France", "Fox", "Florida"] },
    { "cat": "b", "q": "Jak se hláskuje písmeno 'G'?", "a": "Golf", "others": ["George", "Gamma", "Germany", "Gold"] },
    { "cat": "b", "q": "Jak se hláskuje písmeno 'H'?", "a": "Hotel", "others": ["Honza", "Henry", "Holland", "Hawaii"] },
    { "cat": "b", "q": "Jak se hláskuje písmeno 'I'?", "a": "India", "others": ["Ivan", "Italy", "Ice", "Item"] },
    { "cat": "b", "q": "Jak se hláskuje písmeno 'J'?", "a": "Juliett", "others": ["John", "Japan", "Jupiter", "Jersey"] },
    { "cat": "b", "q": "Jak se hláskuje písmeno 'K'?", "a": "Kilo", "others": ["Karel", "King", "Kentucky", "Kilogram"] },
    { "cat": "b", "q": "Jak se hláskuje písmeno 'L'?", "a": "Lima", "others": ["London", "Lemon", "Ludvik", "Love"] },
    { "cat": "b", "q": "Jak se hláskuje písmeno 'M'?", "a": "Mike", "others": ["Mother", "Mexico", "Mars", "Monday"] },
    { "cat": "b", "q": "Jak se hláskuje písmeno 'N'?", "a": "November", "others": ["Noray", "Nancy", "Night", "New York"] },
    { "cat": "b", "q": "Jak se hláskuje písmeno 'O'?", "a": "Oscar", "others": ["Ota", "Ocean", "Orange", "Ontario"] },
    { "cat": "b", "q": "Jak se hláskuje písmeno 'P'?", "a": "Papa", "others": ["Peter", "Paris", "Pepa", "Paul"] },
    { "cat": "b", "q": "Jak se hláskuje písmeno 'Q'?", "a": "Quebec", "others": ["Queen", "Quality", "Quark", "Question"] },
    { "cat": "b", "q": "Jak se hláskuje písmeno 'R'?", "a": "Romeo", "others": ["Ruda", "Radio", "Roger", "Robert"] },
    { "cat": "b", "q": "Jak se hláskuje písmeno 'S'?", "a": "Sierra", "others": ["Sugar", "Samba", "Santiago", "September"] },
    { "cat": "b", "q": "Jak se hláskuje písmeno 'T'?", "a": "Tango", "others": ["Tomas", "Texas", "Tiger", "Target"] },
    { "cat": "b", "q": "Jak se hláskuje písmeno 'U'?", "a": "Uniform", "others": ["Uran", "Uncle", "Unit", "Utah"] },
    { "cat": "b", "q": "Jak se hláskuje písmeno 'V'?", "a": "Victor", "others": ["Vasek", "Victory", "Video", "Village"] },
    { "cat": "b", "q": "Jak se hláskuje písmeno 'W'?", "a": "Whiskey", "others": ["William", "Washington", "Winter", "Water"] },
    { "cat": "b", "q": "Jak se hláskuje písmeno 'X'?", "a": "X-ray", "others": ["Xaver", "Xylophone", "X-box", "X-rayer"] },
    { "cat": "b", "q": "Jak se hláskuje písmeno 'Y'?", "a": "Yankee", "others": ["Yellow", "Yoga", "Yesterday", "Ypsilon"] },
    { "cat": "b", "q": "Jak se hláskuje písmeno 'Z'?", "a": "Zulu", "others": ["Zuzana", "Zebra", "Zero", "Zodiac"] },
    { "cat": "b", "q": "Jak se hláskuje číslice '1'?", "a": "Jedna", "others": ["Raz", "One", "Jednicka", "Prvni"] },
    { "cat": "b", "q": "Jak se hláskuje číslice '2'?", "a": "Dvě", "others": ["Dvojka", "Two", "Druha", "Dva"] },
    { "cat": "b", "q": "Jak se hláskuje číslice '3'?", "a": "Tři", "others": ["Trojka", "Three", "Treti", "Triska"] },
    { "cat": "b", "q": "Jak se hláskuje číslice '4'?", "a": "Čtyři", "others": ["Ctverka", "Four", "Ctvrta", "Ctyrka"] },
    { "cat": "b", "q": "Jak se hláskuje číslice '5'?", "a": "Pět", "others": ["Petka", "Five", "Pata", "Petice"] },
    { "cat": "b", "q": "Jak se hláskuje číslice '6'?", "a": "Šest", "others": ["Sestka", "Six", "Sesta", "Sestice"] },
    { "cat": "b", "q": "Jak se hláskuje číslice '7'?", "a": "Sedm", "others": ["Sedmicka", "Seven", "Sedma", "Sedmice"] },
    { "cat": "b", "q": "Jak se hláskuje číslice '8'?", "a": "Osmička", "others": ["Osum", "Eight", "Osm", "Osmička-nula"] },
    { "cat": "b", "q": "Jak se hláskuje číslice '9'?", "a": "Devět", "others": ["Devitka", "Nine", "Devata", "Devetka"] },
    { "cat": "b", "q": "Jak se hláskuje číslice '0'?", "a": "Nula", "others": ["Zero", "Nic", "O nula", "Prázdno"] },
    { "cat": "b", "q": "Jak se hlásí desetinná čárka v kmitočtu?", "a": "Celých", "others": ["Tečka", "Čárka", "Point", "Decimal"] },
    { "cat": "b", "q": "Jaký je mezinárodní tísňový kmitočet?", "a": "121,5 MHz", "others": ["123,45 MHz", "118,1 MHz", "130,0 MHz", "115,5 MHz"] },
    { "cat": "b", "q": "Jakým slovem uvozujeme pilnostní volání?", "a": "PAN PAN", "others": ["MAYDAY", "SECURITE", "BREAK BREAK", "ATTENTION"] },
    { "cat": "b", "q": "Jak se hlásí čas 16:00 UTC?", "a": "Jedna šest nula nula", "others": ["Šestnáct nula nula", "Čtyři odpoledne", "Šestnáct hodin přesně", "Jedna šestka nula nula"] },
    { "cat": "b", "q": "Co znamená výraz 'POTVRĎTE'?", "a": "Požaduji potvrzení (příjmu a porozumění)", "others": ["Zopakujte hlášení", "Udejte svou polohu", "Přepněte kmitočet", "Ohlaste počet osob"] },
    { "cat": "b", "q": "Co znamená výraz 'ROZUMÍM'?", "a": "Přijal jsem celé vaše poslední vysílání", "others": ["Budu postupovat podle pokynů", "Souhlasím s návrhem", "Čekejte", "Signál je silný"] },
    { "cat": "b", "q": "Co znamená výraz 'PROVEĎTE'?", "a": "Proveďte zamýšlený úkon", "others": ["Opakujte manévr", "Vysílejte znovu", "Rozumím", "Opusťte dráhu"] },
    { "cat": "b", "q": "Co znamená výraz 'OPAKUJTE'?", "a": "Předat celou zprávu nebo její část znovu", "others": ["Změňte kurz", "Vraťte se", "Mluvte hlasitěji", "Zopakujte kód"] },
    { "cat": "b", "q": "Co znamená výraz 'SCHVÁLENO'?", "a": "Povolení k navrhovanému úkonu", "others": ["Slyším vás", "Poloha potvrzena", "Plán přijat", "Můžete odejít"] },
    { "cat": "b", "q": "Co znamená výraz 'KONEC'?", "a": "Tato komunikace je ukončena a neočekávám odpověď", "others": ["Vypínám rádio", "Opouštím prostor", "Čekám", "Předávám"] },
    { "cat": "b", "q": "Jaký je formát pro zkoušku spojení?", "a": "Volaná stanice, volající stanice, Zkouška spojení", "others": ["Jak mě slyšíte?", "Tady ABC, slyšíte mě?", "Zkouška spojení 1-2-3", "Slyšíte mě?"] },
    { "cat": "b", "q": "Co znamená čitelnost 1?", "a": "Nečitelné", "others": ["Čitelné s obtížemi", "Čitelné občas", "Čitelné dobře", "Slyším šum"] },
    { "cat": "b", "q": "Co znamená čitelnost 3?", "a": "Čitelné s obtížemi", "others": ["Nečitelné", "Čitelné občas", "Čitelné dobře", "Dokonale čitelné"] },
    { "cat": "b", "q": "Co znamená čitelnost 5?", "a": "Dokonale čitelné", "others": ["Silný šum", "Slyším vás 5 minut", "Čitelné jen s opakováním", "Zkreslené"] },
    { "cat": "b", "q": "Kdy se používá slovo 'PŘÍJEM'?", "a": "Na konci vysílání, když očekáváme odpověď", "others": ["Vždy", "Pouze v tísni", "Při hlášení polohy", "Při nerozumění"] },
    { "cat": "b", "q": "Jak se hlásí výška 5000 stop?", "a": "Pět tisíc stop", "others": ["Pět nula nula nula", "Hladina padesát", "Pět kilometrů", "Padesát set stop"] },
    { "cat": "b", "q": "Jak se hlásí volací znak letadla OK-ABC?", "a": "Oskar Kilo Alfa Bravo Charlie", "others": ["O K A B C", "Oskara Kila Alfa Bravo Charlie", "ABC", "O.K. Alfa Bravo Charlie"] },
    { "cat": "b", "q": "První volání stanice AFIS (rádio):", "a": "Volaná stanice, volající stanice, poloha, záměr", "others": ["Jen volací znak", "Volaná stanice a počet osob", "Typ a výška", "Dobrý den"] },
    { "cat": "b", "q": "Kmitočet pro komunikaci air-to-air:", "a": "123,450 MHz", "others": ["121,500 MHz", "118,100 MHz", "130,000 MHz", "126,700 MHz"] },
    { "cat": "b", "q": "Kdo má přednost před pilnostní zprávou?", "a": "Zpráva tísňová", "others": ["Meteorologie", "Pokyn k pojždění", "Bezpečnost", "Nikdo"] },
    { "cat": "b", "q": "Jak se hlásí změna kmitočtu?", "a": "Měním na (nový kmitočet)", "others": ["Odcházím", "Ladím jinam", "Končím", "Slyšíme se jinde"] },
    { "cat": "b", "q": "Co je 'Slepé vysílání'?", "a": "Vysílání v situaci, kdy nelze navázat obousměrné spojení", "others": ["Bez odpovídače", "V noci", "Bez licence", "Na zakázaném kmitočtu"] },
    { "cat": "b", "q": "Jak se hlásí směr větru 270 stupňů?", "a": "Dva sedm nula stupňů", "others": ["Dvěstě sedmdesát", "Západní vítr", "Dvě sedmička nula", "Směr 270"] },

    // --- KATEGORIE C: TECHNIKA (101-120) ---
    { "cat": "c", "q": "Co je to nosná vlna?", "a": "Vysokofrekvenční vlnění určené k přenosu informace", "others": ["Vlna, která nese letadlo", "Zvukový signál", "Baterie", "Zpětná vazba"] },
    { "cat": "c", "q": "V jakém pásmu pracují letecké stanice?", "a": "VHF (Very High Frequency)", "others": ["HF", "UHF", "LF", "MF"] },
    { "cat": "c", "q": "Rozsah leteckého pásma VHF:", "a": "118,000 až 136,975 MHz", "others": ["108,000 až 117,900 MHz", "87,5 až 108,0 MHz", "144,000 až 146,000 MHz", "400-470 MHz"] },
    { "cat": "c", "q": "Co způsobuje největší rušení příjmu?", "a": "Systém zapalování motoru", "others": ["Vítr", "Slunce", "Tlak", "Pohyb"] },
    { "cat": "c", "q": "K čemu slouží anténa?", "a": "K přeměně energie na vlny a naopak", "others": ["K vyvážení", "K měření rychlosti", "Ochrana před bleskem", "Dekorace"] },
    { "cat": "c", "q": "Rychlost šíření radiových vln:", "a": "300 000 km/s", "others": ["340 m/s", "100 000 km/h", "300 km/s", "Rychlost zvuku"] },
    { "cat": "c", "q": "Co je to Squelch?", "a": "Šumová brána k potlačení šumu při absenci signálu", "others": ["Zesilovač", "Ladící knoflík", "Pojistka", "Konektor"] },
    { "cat": "c", "q": "Co se stane, když je anténa příliš krátká?", "a": "Odraz energie zpět do vysílače a pokles výkonu", "others": ["Vysílač se přeladí", "Zlepší se zvuk", "Dosah se zdvojnásobí", "Nic"] },
    { "cat": "c", "q": "Typ modulace v letectví:", "a": "Amplitudová modulace (AM)", "others": ["Frekvenční (FM)", "Fázová (PM)", "Digitální", "Pulzní"] },
    { "cat": "c", "q": "Co je to koaxiální kabel?", "a": "Stíněné vedení pro vysokofrekvenční signál", "others": ["Napájení motoru", "Přívod paliva", "Ocelové lanko", "Dvojlinka"] },
    { "cat": "c", "q": "Co ovlivňuje dosah VHF vysílání?", "a": "Výška letadla a přímá viditelnost", "others": ["Vlhkost paliva", "Stáří pilota", "Kapacita", "Typ oleje"] },
    { "cat": "c", "q": "K čemu slouží mikrofon?", "a": "K přeměně zvukových vln na elektrické signály", "others": ["K reprodukci", "K filtrování šumu", "K ukládání", "K ovládání"] },
    { "cat": "c", "q": "Kanálový rozestup v letectví:", "a": "8,33 kHz", "others": ["25 kHz", "100 kHz", "50 kHz", "10 kHz"] },
    { "cat": "c", "q": "Účel statických vybíječů:", "a": "Odvést statickou elektřinu", "others": ["Zlepšit aerodynamiku", "GPS", "Osvětlení", "Vypouštění paliva"] },
    { "cat": "c", "q": "Zdroj energie pro rádio při letu:", "a": "Alternátor nebo generátor", "others": ["Turbína", "Solární panel", "Statická elektřina", "Teplo"] },
    { "cat": "c", "q": "Co znamená zkratka PTT?", "a": "Push-To-Talk (stiskni a mluv)", "others": ["Pilot-To-Tower", "Power-Test", "Position-Track", "Tele-Type"] },
    { "cat": "c", "q": "K čemu slouží sluchátka?", "a": "K nerušenému poslechu a ochraně sluchu", "others": ["Tlak", "Stabilita hlavy", "Vyhřívání", "Hudba"] },
    { "cat": "c", "q": "Proč se nepoužívá FM modulace?", "a": "AM umožňuje slyšet více stanic najednou (při tísni)", "others": ["FM neprojde mraky", "FM je těžká", "Ruší kompas", "Zakázáno armádou"] },
    { "cat": "c", "q": "Co je to 'interkom'?", "a": "Zařízení pro vnitřní hovor mezi posádkou", "others": ["Vnější spojení", "Sledování", "Navigace", "Záložní rádio"] },
    { "cat": "c", "q": "Co se stane při vybití baterie a zastavení motoru?", "a": "Radiostanice přestane fungovat", "others": ["Ruční pohon", "Magnetismus", "Zesílení", "Samo-vysílání"] }
];