const quizData = [
    // --- SEKCE A: RADIOKOMUNIKAČNÍ PŘEDPISY (Dle PDF ČTÚ) ---
    { cat: 'a', q: 'Kdo vykonává zajištění účelného využívání rádiových kmitočtů a správu rádiového spektra?', a: 'Český telekomunikační úřad', others: ['Úřad pro civilní letectví', 'Ministerstvo dopravy', 'Radiokomunikační rada'] },
    { cat: 'a', q: 'Radiokomunikační službou je komunikační činnost, která spočívá v přenosu, vysílání nebo příjmu signálů prostřednictvím:', a: 'rádiových vln', others: ['družicových spojů', 'optických kabelů', 'digitálních protokolů'] },
    { cat: 'a', q: 'Kdo uděluje individuální oprávnění k využívání rádiových kmitočtů?', a: 'Český telekomunikační úřad', others: ['Ministerstvo průmyslu a obchodu', 'Řízení letového provozu', 'Vláda ČR'] },
    { cat: 'a', q: 'Držitel individuálního oprávnění k využívání rádiových kmitočtů je povinen platit za využívání rádiových kmitočtů:', a: 'poplatek dle nařízení vlády o poplatcích', others: ['paušální daň z frekvence', 'členský příspěvek ITU', 'správní poplatek při každém vysílání'] },
    { cat: 'a', q: 'Rádiovým spektrem se rozumí elektromagnetické vlny o kmitočtu (frekvenci):', a: 'nižším než 3000 GHz', others: ['vyšším než 300 MHz', 'v rozsahu 100 kHz až 100 GHz', 'nižším než 1500 MHz'] },
    { cat: 'a', q: 'Rádiové kmitočty z pásma 160 MHz spadají do pásma označovaného jako:', a: 'VHF', others: ['UHF', 'HF', 'SHF'] },
    { cat: 'a', q: 'Státní kontrolu elektronických komunikací vykonává:', a: 'Český telekomunikační úřad', others: ['Policie ČR', 'Úřad pro civilní letectví', 'Nejvyšší kontrolní úřad'] },
    { cat: 'a', q: 'Fyzická osoba vykonávající obsluhu vysílacího rádiového zařízení bez platného průkazu odborné způsobilosti se dopustila:', a: 'přestupku', others: ['trestného činu', 'kázeňského provinění', 'pojistného podvodu'] },
    { cat: 'a', q: 'Za obsluhu vysílacího rádiového zařízení bez platného průkazu odborné způsobilosti lze uložit fyzické osobě pokutu do výše:', a: '100 000 Kč', others: ['50 000 Kč', '10 000 Kč', '1 000 000 Kč'] },
    { cat: 'a', q: 'V mezinárodní volací značce České republiky tvoří první dvě písmena (prefix) vždy dvojice písmen:', a: 'OK nebo OL', others: ['CZ nebo CR', 'OA nebo OB', 'KA nebo KB'] },
    { cat: 'a', q: 'Mezinárodní volací značka letadlové stanice u letounů zapsaných v leteckém rejstříku ČR je:', a: 'OK a další tři písmena', others: ['OK a další dvě písmena', 'OK a čtyři číslice', 'OL a tři písmena'] },
    { cat: 'a', q: 'Falešné volací značky a falešné signály:', a: 'se nesmí používat', others: ['se smí používat jen při výcviku', 'se smí používat v tísni', 'se smí používat po schválení velitelem'] },
    { cat: 'a', q: 'Pohyblivá stanice letecké pohyblivé služby je:', a: 'letadlová stanice', others: ['pozemní stanice', 'mobilní telefon pilota', 'radiomaják'] },
    { cat: 'a', q: 'Pevná služba je:', a: 'radiokomunikační služba mezi stanovenými pevnými body', others: ['služba určená pro komunikaci s letadly na zemi', 'služba, která má pevně stanovený čas vysílání', 'služba pracující na jedné pevné frekvenci'] },
    { cat: 'a', q: 'Nejvyšší prioritu a absolutní přednost má zpráva:', a: 'tísňová', others: ['pilnostní', 'meteorologická', 'státní důležitosti'] },
    { cat: 'a', q: 'Správné pořadí zpráv dle důležitosti (od nejvyšší) je:', a: 'tísňové, pilnostní, o zaměřování, pro bezpečnost letů, meteorologické, o pravidelnosti letů', others: ['tísňové, o bezpečnosti, pilnostní, meteorologické', 'státní, tísňové, meteorologické, o pohybu letadel', 'tísňové, pilnostní, meteorologické, o bezpečnosti letů'] },
    { cat: 'a', q: 'Tísňové volání a tísňová zpráva se vysílají jen na rozkaz:', a: 'velitele nebo osoby odpovědné za loď nebo letadlo', others: ['příslušného řídícího letového provozu', 'majitele letadla', 'kohokoliv, kdo uvidí nebezpečí'] },
    { cat: 'a', q: 'Mezinárodní tísňový kmitočet v radiotelefonii v letecké pohyblivé službě je:', a: '121,5 MHz', others: ['123,45 MHz', '118,1 MHz', '121,0 MHz'] },
    { cat: 'a', q: 'Služba u letadlové nebo lodní stanice podléhá nejvyšší pravomoci:', a: 'velitele nebo osoby, která je odpovědná za letadlo nebo loď', others: ['operátora pozemní stanice', 'Českého telekomunikačního úřadu', 'vlastníka radiostanice'] },
    { cat: 'a', q: 'Doba platnosti průkazů radiotelefonistů (OFL) je stanovena na:', a: '10 let při prvním vydání průkazu', others: ['5 let', 'doživotně', '10 let od data složení zkoušky'] },
    { cat: 'a', q: 'O prodloužení doby platnosti průkazu odborné způsobilosti se žádá:', a: 'písemně, minimálně jeden měsíc před koncem platnosti průkazu', others: ['osobně, v den vypršení platnosti', 'elektronicky, nejpozději rok po vypršení', 'není třeba žádat, prodlužuje se automaticky'] },
    { cat: 'a', q: 'Při žádosti o prodloužení platnosti průkazu je třeba také:', a: 'uhradit příslušný správní poplatek a doložit praxi v obsluze rádiových stanic', others: ['znovu složit praktickou zkoušku', 'předložit potvrzení o zdravotní způsobilosti', 'doložit vlastnictví radiostanice'] },
    { cat: 'a', q: 'V případě, že doba platnosti průkazu již uplynula, může držitel průkazu žádat o nový průkaz bez zkoušky:', a: 'v období do jednoho roku ode dne pozbytí platnosti průkazu', others: ['kdykoliv po vypršení platnosti', 'pouze do jednoho měsíce po vypršení', 'v období do pěti let od pozbytí platnosti'] },
    { cat: 'a', q: 'Doba platnosti průkazů radiotelefonistů se na základě žádosti držitele prodlužuje o:', a: '5 let', others: ['10 let', '2 roky', 'doživotně'] },
    { cat: 'a', q: 'První znak nebo první dva znaky mezinárodní volací značky označují:', a: 'státní příslušnost stanice', others: ['typ letadla', 'kategorii radiostanice', 'domovské letiště'] },
    { cat: 'a', q: 'Stejná volací značka:', a: 'nemůže být přidělena dvěma nebo více provozovatelům stanic', others: ['může být použita letadly stejného typu', 'může být sdílena v rámci jednoho aeroklubu', 'se smí opakovat po 5 letech od vyřazení původní stanice'] },
    { cat: 'a', q: 'Inspekční orgány zemí, které provedou kontrolu vybavení radiové stanice:', a: 'mohou vyžadovat předložení průkazu operátora', others: ['nemají právo kontrolovat průkazy cizích státních příslušníků', 'mohou radiostanici zabavit bez udání důvodu', 'vyžadují pouze technický list přístroje'] },
    { cat: 'a', q: 'Mezinárodní telekomunikační unie (ITU) je:', a: 'specializovanou organizací OSN pro oblast telekomunikací', others: ['evropským úřadem pro frekvenční spektrum', 'sdružením výrobců letecké techniky', 'kontrolním orgánem NATO'] },
    { cat: 'a', q: 'Mezinárodní organizací CEPT se rozumí:', a: 'Evropská konference poštovních a telekomunikačních správ', others: ['Centrální evropský portál telekomunikací', 'Celoevropský protokol pro tísňové volání', 'Certifikační úřad pro rádiová zařízení'] },
    { cat: 'a', q: 'Q-kódem se rozumí:', a: 'kódová skupina tří písmen začínající vždy písmenem Q, která má určitý mezinárodně dohodnutý význam', others: ['zkratka pro dotazy na řízení letového provozu', 'šifrovaný kód pro vojenské letectvo', 'označení kvality příjmu signálu'] },
    { cat: 'a', q: 'Volací značky se přidělují tak, aby nemohly být zaměněny:', a: 's tísňovými, pilnostními a bezpečnostními signály nebo s kódovými zkratkami Q-kódu', others: ['se jmény pilotů nebo typy motorů', 's frekvencemi rozhlasových stanic', 's registračními značkami aut'] },
    { cat: 'a', q: 'Volací značkou je:', a: 'každé poznávací označení stanice přidělené podle Radiokomunikačního řádu, které umožňuje zjištění její totožnosti', others: ['jméno velitele letadla', 'výrobní číslo radiostanice', 'frekvence, na které stanice vysílá'] },
    { cat: 'a', q: 'Telekomunikační tajemství se týká:', a: 'všech osob, které znají obsah rádiových zpráv nebo se dozvěděly o jejich existenci', others: ['pouze zaměstnanců ČTÚ a ŘLP', 'pouze zpráv označených jako TAJNÉ', 'pouze tísňových hlášení'] },
    { cat: 'a', q: 'Každý, kdo se dozví informace o skutečnostech, které jsou předmětem telekomunikačního tajemství:', a: 'je povinen zachovávat o nich mlčenlivost', others: ['je povinen je nahlásit na ČTÚ', 'je smí sdělit pouze rodinným příslušníkům', 'se jich musí okamžitě zapomenout'] },
    { cat: 'a', q: 'Předmětem telekomunikačního tajemství je zejména:', a: 'obsah zpráv přepravovaných sítěmi s výjimkou zpráv určených veřejnosti', others: ['technické parametry vysílaček', 'seznam všech letištních frekvencí', 'aktuální předpověď počasí ATIS'] },



    // --- SEKCE B: RADIOKOMUNIKAČNÍ PROVOZ (1-50) ---
    { cat: 'b', q: 'Letecká pohyblivá služba je:', a: 'pohyblivá služba mezi leteckými stanicemi a letadlovými stanicemi nebo mezi letadlovými stanicemi navzájem', others: ['služba určená pro komunikaci s letadly na zemi pomocí mobilních telefonů', 'služba mezi řízením letového provozu a armádou', 'telekomunikační služba mezi dvěma pevnými body na letišti'] },
    { cat: 'b', q: 'Letecká pevná služba (AFS dle L10) je:', a: 'telekomunikační služba mezi stanovenými pevnými body', others: ['služba určená pro letadla na stojánce', 'radiové spojení mezi věží a radarem', 'služba pro vysílání meteorologických informací'] },
    { cat: 'b', q: 'Letecká rozhlasová služba (dle L10) je:', a: 'služba určená k vysílání informací týkajících se leteckého provozu', others: ['komerční rádio pro posádky letadel', 'služba pro hlášení tísně na frekvenci 121,5 MHz', 'vysílání hudby do sluchátek pilotů'] },
    { cat: 'b', q: 'Pozemní stanice letecké pohyblivé služby je:', a: 'letecká stanice', others: ['letadlová stanice', 'mobilní stanice', 'základnová stanice'] },
    { cat: 'b', q: 'Vysílání pokusných signálů nesmí trvat déle než:', a: '10 vteřin', others: ['5 vteřin', '30 vteřin', '1 minutu'] },
    { cat: 'b', q: 'Při zkušebním vysílání je dokonalá čitelnost uváděna stupněm:', a: '5 (Dokonale čitelné)', others: ['10 (Maximálně čitelné)', '1 (Slabá čitelnost)', '4 (Čitelné)'] },
    { cat: 'b', q: 'Zkušební vysílání musí obsahovat:', a: 'volací značku volané stanice, volací značku letadla, slova „ZKOUŠKA RÁDIA“, používaný kmitočet', others: ['pouze slovo TEST a značku letadla', 'volací značku letadla a aktuální čas', 'volací značku letadla a polohu'] },
    { cat: 'b', q: 'Rychlost hovoru při radiotelefonním spojení nemá převyšovat:', a: '100 slov za minutu', others: ['60 slov za minutu', '150 slov za minutu', '80 slov za minutu'] },
    { cat: 'b', q: 'Radiotelefonní spojení letadlo – země by se mělo provádět:', a: 'všeobecně v jazyce, ve kterém komunikuje pozemní stanice', others: ['vždy v angličtině', 'vždy v mateřském jazyce pilota', 'v jazyce státu, nad kterým letadlo právě letí'] },
    { cat: 'b', q: 'Zprávy musí být vysílány:', a: 'v otevřené řeči a ve schválených frázích', others: ['v kódovaných skupinách', 'v co nejkratším možném čase bez ohledu na fráze', 'pouze v anglickém jazyce'] },
    { cat: 'b', q: 'Při vysílání:', a: 'zachováváme stále stejnou výši hlasu ve všech fázích hovoru', others: ['zvyšujeme hlas při důležitých příkazech', 'mluvíme co nejrychleji, abychom nezdržovali', 'měníme intonaci pro zdůraznění volací značky'] },
    { cat: 'b', q: 'Pořadí zpráv dopravovaných leteckou pohyblivou službou je:', a: 'tísňové, pilnostní, o rádiovém zaměřování, pro zajištění bezpečnosti letů, meteorologické, o pravidelnosti letů', others: ['tísňové, meteorologické, pilnostní, o bezpečnosti letů', 'státní důležitosti, tísňové, o pohybu letadel', 'tísňové, pilnostní, zprávy velitele, počasí'] },
    { cat: 'b', q: 'MAYDAY je radiotelefonní signál:', a: 'tísňové zprávy', others: ['pilnostní zprávy', 'zprávy o počasí', 'zkoušky rádia'] },
    { cat: 'b', q: 'PAN PAN je radiotelefonní signál:', a: 'pilnostní zprávy', others: ['tísňové zprávy', 'zprávy o ukončení provozu', 'zprávy pro cestující'] },
    { cat: 'b', q: 'Tísňová korespondence:', a: 'má přednost před všemi ostatními druhy spojení', others: ['má stejnou prioritu jako pilnostní', 'má přednost před vším vyjma státních zpráv', 'se vysílá pouze na vyžádání věže'] },
    { cat: 'b', q: 'Pilnostní zpráva:', a: 'má přednost před všemi ostatními druhy spojení vyjma tísňového provozu', others: ['má absolutní přednost přede vším', 'má nižší prioritu než meteorologické zprávy', 'se vysílá pouze při poruše motoru'] },
    { cat: 'b', q: 'Tísňový a pilnostní provoz musí být zahájen na kmitočtu:', a: 'který je v dané chvíli používán', others: ['vždy na 121,5 MHz', 'vždy na frekvenci nejbližšího letiště', 'na kanálu 16'] },
    { cat: 'b', q: 'Po volání letecké stanice, na které tato stanice neodpoví, je letadlová stanice povinna:', a: 'vyčkat nejméně 10 sekund, než provede další volání', others: ['ihned opakovat volání s vyšší hlasitostí', 'změnit frekvenci', 'vyčkat 1 minutu'] },
    { cat: 'b', q: 'Jména, zkratky a slova, jejichž výslovnost může vyvolat pochybnost, se musí:', a: 'hláskovat', others: ['zopakovat dvakrát po sobě', 'vyslovit velmi pomalu', 'napsat do letového deníku'] },
    { cat: 'b', q: 'Letadlová stanice udržuje rádiové spojení s řídící stanicí:', a: 'vždy, je-li to možné', others: ['pouze při vzletu a přistání', 'pouze v řízeném prostoru', 'jen pokud o to řídící požádá'] },
    { cat: 'b', q: 'Letadlová stanice potvrzuje příjem důležitých zpráv řízení letového provozu:', a: 'jejich opakováním a připojením vlastní volací značky', others: ['pouze slovem ROZUMÍM', 'pouze svou volací značkou', 'krátkým zaklíčováním (dvakrát)'] },
    { cat: 'b', q: 'Za letu musí letadlová stanice:', a: 'udržovat stálou poslechovou hlídku', others: ['mít zapnuté rádio jen v blízkosti letišť', 'vysílat svou polohu každých 5 minut', 'poslouchat rádio jen při změně kurzu'] },
    { cat: 'b', q: 'Letadlo přechází z jednoho rádiového kmitočtu na druhý:', a: 'z příkazu letecké stanice v souladu s dohodnutými postupy', others: ['podle uvážení pilota', 'vždy přesně na hranici FIRu', 'jen pokud je signál slabý'] },
    { cat: 'b', q: 'Jestliže letadlová stanice není schopna navázat spojení s leteckou stanicí na určeném kmitočtu:', a: 'pokusí se navázat spojení s jiným letadlem nebo jinými leteckými stanicemi', others: ['okamžitě zahájí nouzové vysílání Mayday', 'se vrátí na letiště vzletu', 'vypne radiostanici'] },
    { cat: 'b', q: 'Letadlo za letu:', a: 'nesmí měnit svou volací značku', others: ['může změnit značku po přeletu hranic', 'mění značku při každé změně frekvence', 'smí značku zkrátit bez oslovení věží'] },
    { cat: 'b', q: 'Poznávací značka civilního letadla je složena:', a: 'ze značky státní příslušnosti a rejstříkové značky', others: ['ze jména majitele a čísla motoru', 'z typu letadla a roku výroby', 'pouze z pěti náhodných písmen'] },
    { cat: 'b', q: 'Volací značku letadla lze tvořit:', a: 'radiotelefonním označením provozovatele letadla, za kterým následuje označení (číslo) letu', others: ['pouze jménem pilota', 'jménem letiště a typem letadla', 'zkratkou ICAO a datem'] },
    { cat: 'b', q: 'Volací značka letecké stanice je tvořena:', a: 'zeměpisným názvem její polohy a službou, která je k dispozici', others: ['jménem vedoucího stanoviště a frekvencí', 'náhodným slovem a číslem kanálu', 'zkratkou letiště a slovem TOWER'] },
    { cat: 'b', q: 'Ve volací značce letecké stanice přibližovacího stanoviště může být název:', a: 'APPROACH', others: ['ARRIVAL', 'RADAR', 'VĚŽ'] },
    { cat: 'b', q: 'Ve volací značce letecké stanice pro neřízená letiště je název:', a: 'INFO nebo RADIO', others: ['TOWER', 'GROUND', 'CONTROL'] },
    { cat: 'b', q: 'Zkrácenou volací značku použije letadlová stanice:', a: 'pouze v případě, že byla tímto způsobem oslovena leteckou stanicí', others: ['kdykoliv po prvním navázání spojení', 'vždy, aby se šetřil čas na frekvenci', 'pouze v tísni'] },
    { cat: 'b', q: 'Správné zkrácení volací značky OKABC je:', a: 'OBC', others: ['ABC', 'OK-BC', 'KABC'] },
    { cat: 'b', q: 'Fráze „VYSÍLÁM NASLEPO“ se použije:', a: 'při neúspěšném navázání spojení', others: ['při letu v mracích', 'při selhání přijímače u věže', 'při testování nového rádia'] },
    { cat: 'b', q: 'Jestliže letadlová stanice není schopna navázat spojení s leteckou stanicí na určeném kmitočtu:', a: 'pokusí se o navázání spojení na jiném kmitočtu pro danou trať', others: ['vysílá Mayday na frekvenci 121,5', 'ihned přistane na nejbližším poli', 'přestane vysílat a letí dál'] },
    { cat: 'b', q: 'Všechna čísla se vyslovují:', a: 'jednotlivě, s výjimkou čísel souvisejících s výškou, oblačností, dohledností a dráhovou dohledností', others: ['vždy jako celá čísla (např. sto dvacet pět)', 'vždy jednotlivě bez výjimek', 'vždy v angličtině'] },
    { cat: 'b', q: 'Rádiové spojení může být ukončeno:', a: 'na pokyn letecké stanice', others: ['kdykoliv pilot potřebuje klid', 'vždy po opuštění řízeného prostoru', 'při dosažení cestovní hladiny'] },
    { cat: 'b', q: 'V radiotelefonním provozu se kmitočet 119,000 MHz vyjadřuje:', a: 'JEDNA JEDNA DEVĚT ČÁRKA NULA', others: ['STODEVATÁCT ČÁRKA NULA', 'STODEVATÁCT', 'JEDNA JEDNA DEVĚT CELÁ NULA NULA NULA'] },
    { cat: 'b', q: 'V radiotelefonním provozu se kmitočet 121,500 MHz vyjadřuje:', a: 'JEDNA DVA JEDNA ČÁRKA PĚT', others: ['STO DVACET JEDNA PĚT', 'JEDNA DVA JEDNA PĚT SET', 'TÍSŇOVÁ FREKVENCE'] },
    { cat: 'b', q: 'V radiotelefonním provozu se kmitočet 121,050 MHz vyjadřuje:', a: 'JEDNA DVA JEDNA ČÁRKA NULA PĚT NULA', others: ['STO DVACET JEDNA ČÁRKA NULA PADESÁT', 'JEDNA DVA JEDNA ČÁRKA NULA PĚT', 'JEDNA DVA JEDNA NULA PĚT'] },
    { cat: 'b', q: 'V radiotelefonním provozu v pásmech VKV se vysílací kanál vyjadřuje:', a: 'čtyřmi nebo šesti číslicemi', others: ['vždy třemi číslicemi', 'názvem kanálu', 'dvěma číslicemi'] },
    { cat: 'b', q: 'V radiotelefonním provozu se kmitočet 118,055 MHz vyjadřuje:', a: 'JEDNA JEDNA OSUM ČÁRKA NULA PĚT PĚT', others: ['STODEVATÁCT ČÁRKA NULA PADESÁT PĚT', 'JEDNA JEDNA OSUM NULA PĚT PĚT', 'STO OSMNÁCT CELÁ NULA PADESÁT PĚT'] },
    { cat: 'b', q: 'Hláskování písmene A (Národní / Mezinárodní):', a: 'Adam / Alpha', others: ['Alena / Alpha', 'Adam / Alfa', 'Antonín / Alpha'] },
    { cat: 'b', q: 'Hláskování písmene E (Národní / Mezinárodní):', a: 'Emil / Echo', others: ['Eva / Echo', 'Emil / Element', 'Emanuel / Echo'] },
    { cat: 'b', q: 'Hláskování písmene I (Národní / Mezinárodní):', a: 'Ivan / India', others: ['Igor / India', 'Ivan / Indigo', 'Ivana / India'] },
    { cat: 'b', q: 'Hláskování písmene B (Národní / Mezinárodní):', a: 'Božena / Bravo', others: ['Bohumil / Bravo', 'Božena / Beta', 'Barbora / Bravo'] },
    { cat: 'b', q: 'Hláskování písmene F (Národní / Mezinárodní):', a: 'František / Foxtrot', others: ['Filip / Foxtrot', 'František / Fox', 'Ferdinand / Foxtrot'] },
    { cat: 'b', q: 'Hláskování písmene J (Národní / Mezinárodní):', a: 'Josef / Juliett', others: ['Jan / Juliett', 'Josef / Juliet', 'Jaroslav / Juliett'] },
    { cat: 'b', q: 'Hláskování písmene C (Národní / Mezinárodní):', a: 'Cyril / Charlie', others: ['Cenek / Charlie', 'Cyril / Charley', 'Cyprián / Charlie'] },
    { cat: 'b', q: 'Hláskování písmene G (Národní / Mezinárodní):', a: 'Gustav / Golf', others: ['Gabriel / Golf', 'Gustav / George', 'Gérard / Golf'] },
    { cat: 'b', q: 'Hláskování písmene K (Národní / Mezinárodní):', a: 'Karel / Kilo', others: ['Kristián / Kilo', 'Karel / King', 'Kamila / Kilo'] },
    { cat: 'b', q: 'Správný Q-kód pro „tlak indikující nadmořskou výšku, přepočtený na střední hladinu moře“ je:', a: 'QNH', others: ['QFE', 'QNE', 'QDM'] },
    { cat: 'b', q: 'Správný Q-kód pro „magnetický kurs pro směr k zaměřovači“ je:', a: 'QDM', others: ['QDR', 'QUJ', 'QNH'] },
    { cat: 'b', q: 'Správný Q-kód pro „žádost o zaměření“ je:', a: 'QDL', others: ['QDM', 'QTE', 'QDR'] },
    { cat: 'b', q: 'Správná zkratka pro „vzletová a přistávací dráha“ je:', a: 'RWY', others: ['TWY', 'VPD', 'APN'] },
    { cat: 'b', q: 'Správná zkratka pro „automatická informační služba koncové řízené oblasti“ je:', a: 'ATIS', others: ['AFIS', 'METAR', 'VOLMET'] },
    { cat: 'b', q: 'Správná zkratka pro „letová informační oblast“ je:', a: 'FIR', others: ['CTR', 'TMA', 'FIS'] },
    { cat: 'b', q: 'Správná zkratka pro „kmitočet“ je:', a: 'FREQ', others: ['FQ', 'KHZ', 'FRQ'] },
    { cat: 'b', q: 'Zkušební vysílání (ZKOUŠKA RÁDIA) musí obsahovat:', a: 'volací značku volané stanice, volací značku letadla, slova „ZKOUŠKA RÁDIA“, používaný kmitočet', others: ['pouze identifikaci letadla a sílu signálu', 'volací značku letadla a čas', 'zkratku RADIO CHECK a polohu'] },
    { cat: 'b', q: 'Kód QFE se vztahuje k:', a: 'tlaku vzduchu vztaženému k nadmořské výšce letiště', others: ['tlaku přepočtenému na hladinu moře', 'standardnímu tlaku 1013,25 hPa', 'teplotě na prahu dráhy'] },
    { cat: 'b', q: 'V případě, že letadlo stojí na ploše letiště a hodnota tlaku je nastavena na QFE, bude výškoměr ukazovat:', a: 'nulu', others: ['nadmořskou výšku letiště', 'standardní tlakovou hladinu', 'výšku 1013 stop'] },
    { cat: 'b', q: 'Odchylky od spisovné češtiny (specifické tvary) při vysílání čísel v radiotelefonii jsou u číslic:', a: '2, 4, 7, 8', others: ['1, 3, 5, 9', '0, 6, 8', 'všechna čísla se hlásí spisovně'] },
    { cat: 'b', q: 'Nastavení výškoměru na hodnotu 1000 hPa se vysílá takto:', a: 'jeden tisíc', others: ['tisíc', 'jedna nula nula nula', 'jedna nula nula nula hPa'] },
    { cat: 'b', q: 'Nastavení výškoměru na hodnotu 1009 hPa se vysílá takto:', a: 'QNH JEDNA NULA NULA DEVĚT', others: ['tisíc devět', 'jeden tisíc devět', 'jedna nula nula devět'] },
    { cat: 'b', q: 'Letová hladina FL 300 se vysílá takto:', a: 'letová hladina TŘI STA', others: ['letová hladina TŘI NULA NULA', 'tři sta stop', 'hladina TŘI-KA NULA NULA'] },
    { cat: 'b', q: 'Letová hladina FL 180 se vysílá takto:', a: 'letová hladina JEDEN OSUM NULA', others: ['letová hladina STO OSMDESÁT', 'letová hladina JEDNA OSM NULA', 'hladina JEDEN OSUM DESET'] },
    { cat: 'b', q: 'Potvrzení příjmu leteckou stanicí musí obsahovat:', a: 'volací značku letadla, za kterou následuje (je-li to nutné) volací značka letecké stanice', others: ['pouze slovo ROZUMÍM', 'čas přijetí zprávy', 'slovo PŘÍJEM'] },
    { cat: 'b', q: 'Rádiové spojení může být ukončeno:', a: 'na pokyn letecké stanice', others: ['ihned po přistání bez hlášení', 'při opuštění mraků', 'podle uvážení pilota'] },
    { cat: 'b', q: 'Volací znak INFORMATION je přiřazen:', a: 'letovům informačním střediskům (např. FIC Praha) a letištím poskytujícím službu AFIS', others: ['pouze stanovištím TWR', 'všem neřízeným letištím bez výjimky', 'meteorologické službě'] },
    { cat: 'b', q: 'Volací znak INFORMATION je přiřazen (z hlediska středisek):', a: 'letovým informačním střediskům např. FIC Praha', others: ['přibližovací službě APP', 'oblastnímu řízení radar', 'letištní ploše GROUND'] },
    { cat: 'b', q: 'Fráze „ČEKEJTE“ znamená:', a: 'čekejte, zavolám Vás', others: ['vypněte motory', 'zůstaňte v pořadí na přistání', 'nepoužívejte rádio příštích 5 minut'] },
    { cat: 'b', q: 'Fráze „KONEC“ znamená:', a: 'rozhovor je ukončen a neočekává se odpověď', others: ['vypínám radiostanici', 'přepínám na jinou frekvenci', 'slyším vás špatně'] },
    { cat: 'b', q: 'Fráze „PROVEDU“ znamená:', a: 'rozumím Vaší zprávě a budu podle ní postupovat', others: ['právě provádím úkon', 'rozuměl jsem, ale nemohu provést', 'ano, to je správně'] },
    { cat: 'b', q: 'Fráze „POTVRĎTE“ znamená:', a: 'potvrďte mi, že jste zprávu přijal a rozuměl jí', others: ['potvrzuji, že jsem rozuměl', 'opakujte poslední vysílání', 'schvaluji váš požadavek'] },
    { cat: 'b', q: 'Fráze „PŘÍJEM“ znamená:', a: 'moje vysílání skončilo, očekávám Vaši odpověď', others: ['slyším vás velmi dobře', 'rozumím, končím', 'uvolněte frekvenci'] },
    { cat: 'b', q: 'Fráze „ROZUMÍM“ znamená:', a: 'přijal jsem vše z Vašeho posledního vysílání', others: ['provedu váš příkaz', 'souhlasím s vaším návrhem', 'opakujte kurz'] },
    { cat: 'b', q: 'Fráze „SCHVÁLENO“ znamená:', a: 'povolení pro požadovaný úkon je schváleno', others: ['můžete vzlétnout', 'vaše zpráva je čitelná', 'rozumím'] },
    { cat: 'b', q: 'Fráze „NEGATIV“ znamená:', a: 'povolení není potvrzeno – to není správné – ne', others: ['slyšitelnost 1', 'zrušte letový plán', 'nepotvrzuji příjem'] },
    { cat: 'b', q: 'Fráze „OPAKUJTE“ znamená:', a: 'opakujte vše nebo následující část Vašeho posledního vysílání', others: ['opakuji své poslední hlášení', 'změňte frekvenci', 'mluvte hlasitěji'] },
    { cat: 'b', q: 'Fráze „SPRÁVNĚ“ znamená:', a: 'to je správné', others: ['rozumím', 'schváleno', 'opakujte'] },
    { cat: 'b', q: 'Fráze „VZLET SCHVÁLEN“:', a: 'není přípustná', others: ['se používá na řízených letištích', 'se používá v tísni', 'se hlásí jako VZLET POVOLEN'] },
    { cat: 'b', q: 'Simplexní provoz je způsob provozu rádiové stanice, který:', a: 'využívá jeden nebo dva kmitočty a umožňuje přenos zpráv střídavě v obou směrech (není možný současný příjem během vysílání)', others: ['umožňuje mluvit i poslouchat současně', 'funguje pouze na digitálních frekvencích', 'je vyhrazen pro tísňové volání'] },
    { cat: 'b', q: 'Duplexní provoz je způsob provozu rádiové stanice, který:', a: 'umožňuje současný přenos zpráv oběma směry a vyžaduje současné využívání dvou kmitočtů', others: ['umožňuje mluvit dvěma lidem na jednom kmitočtu', 'se používá pro hlášení polohy', 'nevyžaduje anténu'] },
    { cat: 'b', q: 'Při frázi MEZERA MEZERA pro dvě letadlové stanice, pořadí pro odpovědi volaných stanic je následující:', a: 'odpovídá druhá oslovená stanice', others: ['odpovídají obě stanice současně', 'odpovídá první oslovená stanice', 'stanice neodpovídají, jen čekají'] },

    // --- SEKCE C: ELEKTROTECHNIKA A RADIOTECHNIKA (1-31) ---
    { cat: 'c', q: 'Paralelně řazené akumulátory:', a: 'umožňují dodávat větší proud', others: ['zvyšují celkové napětí', 'mají menší kapacitu', 'nelze je propojit'] },
    { cat: 'c', q: 'Sériově řazené akumulátory:', a: 'se zapojují pro zvýšení dodávaného napětí', others: ['umožňují dodávat větší proud', 'snižují celkový odpor', 'se zapojují pro zvýšení kapacity'] },
    { cat: 'c', q: 'Jmenovité napětí článku olověného akumulátoru je:', a: '2 V', others: ['1,2 V', '1,5 V', '12 V'] },
    { cat: 'c', q: 'Jmenovité napětí článku alkalického akumulátoru je:', a: '1,2 V', others: ['2 V', '1,5 V', '9 V'] },
    { cat: 'c', q: 'Jmenovité napětí suchého galvanického článku je:', a: '1,5 V', others: ['1,2 V', '2 V', '3 V'] },
    { cat: 'c', q: 'Suché galvanické články:', a: 'nelze dobíjet', others: ['se musí před použitím nabít', 'lze dobíjet pouze v letectví', 'mají neomezenou životnost'] },
    { cat: 'c', q: 'Antény dělíme podle směru vysílání nebo příjmu na:', a: 'směrové a všesměrové', others: ['dlouhé a krátké', 'aktivní a pasivní', 'vertikální a horizontální'] },
    { cat: 'c', q: 'Všesměrová anténa má vyzařovací charakteristiku:', a: 'kruhovou', others: ['osmičkovou', 'přímkovou', 'všemi směry v kulové ploše'] },
    { cat: 'c', q: 'Všesměrová anténa musí přijímat nebo vysílat stejně všemi směry:', a: 'v horizontální rovině', others: ['ve vertikální rovině', 've všech úhlech současně', 'pouze směrem k zemi'] },
    { cat: 'c', q: 'Půlvlnný dipól:', a: 'může být směrová i všesměrová anténa, záleží na jeho orientaci k zemskému povrchu', others: ['je vždy jen směrová anténa', 'je vždy jen všesměrová anténa', 'v letectví se nepoužívá'] },
    { cat: 'c', q: 'Půlvlnný dipól umístěný rovnoběžně se zemským povrchem:', a: 'má v horizontální rovině osmičkovou vyzařovací charakteristiku', others: ['má kruhovou charakteristiku', 'vyzařuje pouze směrem nahoru', 'nemá žádnou vyzařovací charakteristiku'] },
    { cat: 'c', q: 'Vztah mezi délkou vlny (λ) a kmitočtem (f), když c je rychlost světla, je:', a: 'f = c / λ', others: ['f = c * λ', 'f = λ / c', 'f = c + λ'] },
    { cat: 'c', q: 'Který typ modulace mění kmitočet vysokofrekvenčního signálu v závislosti na přiváděném modulačním napětí?', a: 'kmitočtová modulace', others: ['amplitudová modulace', 'fázová modulace', 'pulzní modulace'] },
    { cat: 'c', q: 'Ampérmetr a voltmetr se při měření zařazují:', a: 'ampérmetr do série se spotřebičem, voltmetr paralelně ke spotřebiči', others: ['oba paralelně', 'oba do série', 'voltmetr do série, ampérmetr paralelně'] },
    { cat: 'c', q: 'V suchém prostředí považujeme za bezpečná napětí při dotyku živých částí:', a: 'stejnosměrné do 60 V a střídavé do 25 V', others: ['stejnosměrné do 220 V', 'střídavé do 50 V', 'jakékoliv napětí z baterie'] },
    { cat: 'c', q: 'Při úrazu elektrickým proudem (základní postup):', a: 'vyprostíme postiženého, zavoláme záchranku, při selhání funkcí zahájíme resuscitaci masáží srdce', others: ['ihned podáme tekutiny', 'vyčkáme na příjezd policie', 'přikryjeme postiženého mokrým hadrem'] },
    { cat: 'c', q: 'Funkce „SQUELCH“ VKV radiostanice je určena:', a: 'k potlačení slabších rušivých signálů včetně vlastního šumu přijímače', others: ['k zesílení hlasu vysílajícího', 'k ladění antény', 'k automatickému přepínání kanálů'] },
    { cat: 'c', q: 'Údaj elektrické napětí 2 V lze také zapsat:', a: '2000 mV', others: ['0,2 kV', '200 mV', '20 mV'] },
    { cat: 'c', q: 'Kmitočet 406 MHz lze také zapsat:', a: '0,406 GHz', others: ['4,06 GHz', '40 600 kHz', '0,0406 GHz'] },
    { cat: 'c', q: 'Délka rádiové vlny v pásmu 160 MHz (VHF) je:', a: 'cca. 2 m', others: ['cca. 10 m', 'cca. 50 cm', 'cca. 12 m'] },
    { cat: 'c', q: 'Vztah mezi napětím (U), proudem (I) a odporem (R) je (Ohmův zákon):', a: 'U = R * I', others: ['U = R / I', 'U = I / R', 'R = U * I'] },
    { cat: 'c', q: 'Vztah mezi výkonem (P), napětím (U) a proudem (I) je:', a: 'P = U * I', others: ['P = U / I', 'P = I / U', 'P = U + I'] },
    { cat: 'c', q: 'Radiostanice odebírající z baterie 12 V proud 500 mA má příkon:', a: '6 W', others: ['60 W', '600 W', '24 W'] },
    { cat: 'c', q: 'Tři dobré vodiče elektřiny jsou:', a: 'měď, zlato, stříbro', others: ['hliník, plast, voda', 'železo, vzduch, rtuť', 'sklo, měď, stříbro'] },
    { cat: 'c', q: 'Čtyři dobré izolanty jsou:', a: 'sklo, vzduch, plast, porcelán', others: ['guma, měď, sklo, papír', 'vzduch, zlato, plast, suché dřevo', 'porcelán, stříbro, PVC, vakuum'] },
    { cat: 'c', q: 'Ke zdroji 10 V jsou připojeny dva odpory 10 Ω zapojené do série. Odebíraný příkon činí:', a: '5 W', others: ['10 W', '20 W', '100 W'] },
    { cat: 'c', q: 'Radiotechnická součástka je identifikována jako kondenzátor, pokud se její hodnota měří v:', a: 'pF', others: ['mH', 'Ω', 'W'] },
    { cat: 'c', q: 'Výstupním výkonem stanice se rozumí:', a: 'výkon koncového stupně vysílače dodávaný do napaječe anténního systému', others: ['příkon odebíraný z baterie', 'akustický výkon reproduktoru', 'zisk antény v decibelech'] },
    { cat: 'c', q: 'Je možné vysílat bez antény?', a: 'ne, hrozí poškození radiostanice', others: ['ano, ale signál bude slabý', 'ano, anténa je potřeba jen pro příjem', 'pouze na tísňové frekvenci'] },
    { cat: 'c', q: 'Co NENÍ možné dělat, když máme stisknuté tlačítko pro vysílání (PTT)?', a: 'přijímat jiné vysílání', others: ['mluvit', 'spotřebovávat energii z baterie', 'vysílat volací značku'] },
    { cat: 'c', q: 'V jakém kmitočtovém pásmu pracuje letadlová VHF radiostanice?', a: '118–137 MHz', others: ['108–118 MHz', '144–146 MHz', '88–108 MHz'] }
];
